import { Box, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@mui/material'
import { useQuery } from '@tanstack/react-query'
import { api } from '../api'
import { ErrorState, LoadingState } from '../components/LoadingState'
import type { Paged } from '../types'
interface Audit {id:number;userName?:string;at:string;entityName:string;entityId:string;action:string;previousValue?:string;newValue?:string}
const actions:Record<string,string>={Create:'Creación',Update:'Actualización',Delete:'Eliminación',Unlink:'Desvinculación',IdentificationImport:'Importación de identificación',TicketUpdate:'Actualización de ticket',BulkAssign:'Asignación masiva',GroupConfirm:'Confirmación grupal',OccupantsUpdate:'Cambio de ocupantes',Close:'Cierre',Reopen:'Reapertura',PasswordReset:'Restablecimiento de contraseña',ProtectionBlocked:'Intento bloqueado por protección'}
const entities:Record<string,string>={Passenger:'Pasajero',RoomReservation:'Habitación',FlightBooking:'Reserva aérea',PassengerFlight:'Ticket individual',BaggageEntitlement:'Equipaje',TripTransferStatus:'Transfer grupal',FollowUp:'Seguimiento',User:'Usuario',Attachment:'Adjunto',AttachmentLink:'Vínculo de adjunto'}
const translated=(value?:string)=>value?.replaceAll('ToVerify','Por verificar').replaceAll('InProgress','En gestión').replaceAll('NotIncluded','No incluido').replaceAll('NotApplicable','No aplica').replaceAll('Confirmed','Confirmado').replaceAll('Ready','Listo').replaceAll('Pending','Pendiente').replaceAll('Attention','Atención')
export function AuditPage(){const q=useQuery({queryKey:['audit'],queryFn:()=>api<Paged<Audit>>('/api/audit?page=1&pageSize=100')});if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error}/>;return <Stack spacing={3}><Box><Typography variant="h1">Auditoría</Typography><Typography color="text.secondary">Últimas {q.data!.items.length} acciones registradas.</Typography></Box><TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell>Fecha</TableCell><TableCell>Usuario</TableCell><TableCell>Entidad</TableCell><TableCell>Acción</TableCell><TableCell>Cambio resumido</TableCell></TableRow></TableHead><TableBody>{q.data!.items.map(x=><TableRow key={x.id}><TableCell>{new Date(x.at).toLocaleString('es-PY')}</TableCell><TableCell>{x.userName??'Sistema'}</TableCell><TableCell>{entities[x.entityName]??x.entityName}<Typography variant="caption" display="block">{x.entityId}</Typography></TableCell><TableCell>{actions[x.action]??x.action}</TableCell><TableCell sx={{maxWidth:420,wordBreak:'break-word'}}><Typography variant="caption">Antes: {translated(x.previousValue)??'—'}</Typography><br/><Typography variant="caption">Después: {translated(x.newValue)??'—'}</Typography></TableCell></TableRow>)}</TableBody></Table></TableContainer></Stack>}
