import AssignmentLateIcon from '@mui/icons-material/AssignmentLate'
import SwapHorizIcon from '@mui/icons-material/SwapHoriz'
import { Alert, Box, Button, Card, CardActionArea, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, Paper, Stack, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, putJson } from '../api'
import { useAuth } from '../auth/AuthProvider'
import { ErrorState, LoadingState } from '../components/LoadingState'
import type { DashboardData } from '../types'

export function DashboardPage(){
  const navigate=useNavigate(),client=useQueryClient(),auth=useAuth();const [confirm,setConfirm]=useState(false);const [notes,setNotes]=useState('')
  const query=useQuery({queryKey:['dashboard'],queryFn:()=>api<DashboardData>('/api/dashboard')})
  const transfer=useMutation({mutationFn:(confirmed:boolean)=>putJson('/api/transfer',{isConfirmed:confirmed,notes,version:query.data!.transfer.version}),onSuccess:async()=>{setConfirm(false);await client.invalidateQueries({queryKey:['dashboard']})}})
  if(query.isLoading)return <LoadingState/>;if(query.error)return <ErrorState error={query.error} retry={()=>void query.refetch()}/>;const d=query.data!;const editable=auth.user?.roles.some(x=>x==='Administrator'||x==='Editor');const hasMissing=d.priorityActions.length>0||!d.transfer.isConfirmed||!d.tripReadiness.allPassengersReady
  return <Stack spacing={3}><Box><Typography variant="h1">Estado del viaje</Typography><Typography color="text.secondary">Lectura rápida de preparación, riesgos y próxima acción.</Typography></Box>
    <Alert severity={hasMissing?'error':'success'} variant="filled" action={hasMissing&&<Button color="inherit" onClick={()=>navigate('/gestion/pendientes')}>Ver pendientes</Button>}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1}><Box><b>{hasMissing?'Todavía faltan entregables para cerrar el viaje':'El viaje está listo'}</b><div>{d.tripReadiness.progressPercent}% de preparación global · {d.priorityActions.map(x=>`${x.count} ${x.title.toLowerCase()}`).join(' · ')}</div></Box><Chip label={hasMissing?'Atención':'Listo'} color={hasMissing?'error':'success'}/></Stack></Alert>
    <Box sx={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,190px),1fr))',gap:2}}>{d.kpis.map(k=><Card key={k.key}><CardActionArea onClick={()=>navigate(k.filter.startsWith('/')?k.filter:`/gestion/pasajeros?${k.filter}`)} sx={{height:'100%',minHeight:44}}><CardContent><Typography color="text.secondary" fontWeight={700}>{k.label}</Typography><Typography variant="h4" fontWeight={850} my={1}>{k.value}<Typography component="span" color="text.secondary" fontSize="1rem"> / {k.total}</Typography></Typography><LinearProgress variant="determinate" value={k.percent} color={k.key==='attention'?'error':k.percent===100?'success':'secondary'} sx={{height:8,borderRadius:8}}/><Typography variant="caption">{k.percent}%</Typography></CardContent></CardActionArea></Card>)}</Box>
    <Paper sx={{p:{xs:2,sm:3}}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Stack direction="row" spacing={1.5}><SwapHorizIcon color={d.transfer.isConfirmed?'success':'warning'}/><Box><Typography variant="h2">Transfer grupal</Typography><Typography color="text.secondary">Confirmación única para todo el viaje; no se asigna por pasajero.</Typography>{d.transfer.updatedBy&&<Typography variant="caption">Último cambio: {d.transfer.updatedBy}</Typography>}</Box></Stack><Stack alignItems={{sm:'flex-end'}} gap={1}><Chip label={d.transfer.isConfirmed?'Confirmado':'Pendiente'} color={d.transfer.isConfirmed?'success':'warning'}/>{editable&&<Button variant={d.transfer.isConfirmed?'outlined':'contained'} onClick={()=>{setNotes(d.transfer.notes??'');setConfirm(true)}}>{d.transfer.isConfirmed?'Revisar estado':'Confirmar transfer'}</Button>}</Stack></Stack></Paper>
    <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'1.35fr 1fr'},gap:3}}><Paper sx={{p:2}}><Typography variant="h2" mb={2}>Las cinco categorías</Typography><Stack spacing={2}>{d.categories.map(c=><Box key={c.key}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>{c.label}</Typography><Typography fontWeight={800}>{c.resolvedPercent}%</Typography></Stack><LinearProgress variant="determinate" value={c.resolvedPercent} color={c.resolvedPercent===100?'success':'secondary'} sx={{height:10,borderRadius:5,my:.75}}/><Typography variant="caption" color="text.secondary">{c.confirmed} confirmados · {c.notApplicable} no aplica · {c.pending} por verificar · {c.inProgress} en gestión · {c.notIncluded} no incluidos</Typography></Box>)}</Stack></Paper><Paper sx={{p:2}}><Typography variant="h2" mb={2}>Acciones prioritarias</Typography><Stack spacing={1.5}>{d.priorityActions.length===0?<Alert severity="success">No hay acciones prioritarias.</Alert>:d.priorityActions.map(a=><Alert key={a.title} severity={a.severity==='critical'?'error':a.severity==='warning'?'warning':a.severity==='success'?'success':'info'} icon={<AssignmentLateIcon/>} onClick={()=>navigate(a.filter.startsWith('globalTransfer')?'/gestion?transfer=1':a.filter.startsWith('/')?a.filter:`/gestion/pasajeros?${a.filter}`)} sx={{cursor:'pointer'}}><b>{a.count}</b> · {a.title}</Alert>)}</Stack></Paper></Box>
    <Paper sx={{p:2}}><Typography variant="h2" mb={2}>Resumen por operadora</Typography><Box sx={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,250px),1fr))',gap:2}}>{d.operators.map(o=><Card key={o.name} variant="outlined"><CardContent><Typography fontWeight={850}>{o.name}</Typography><Typography>{o.passengers} pasajeros · {o.rooms} habitaciones</Typography><Typography color="success.main" fontWeight={700}>{o.confirmedRooms} habitaciones confirmadas</Typography>{o.alerts.map(a=><Alert key={a} severity="info" sx={{mt:1}}>{a}</Alert>)}</CardContent></Card>)}</Box></Paper>
    <Paper sx={{p:2}}><Typography variant="h2" mb={2}>Resumen por aerolínea</Typography><Box sx={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,220px),1fr))',gap:2}}>{d.airlines.map(airline=><Card key={airline.name} variant="outlined"><CardContent><Typography fontWeight={850}>{airline.name.replace(/ \([A-Z]{2}\)$/,'')}</Typography><Typography>{airline.passengers} pasajeros</Typography></CardContent></Card>)}</Box></Paper>
    <Paper sx={{p:2}}><Typography variant="h2" mb={2}>Actividad reciente</Typography>{d.recentActivity.length===0?<Typography color="text.secondary">Todavía no hay cambios auditados.</Typography>:<Stack divider={<Box sx={{borderTop:'1px solid',borderColor:'divider'}}/>}>{d.recentActivity.map(a=><Box key={a.id} py={1}><Typography fontWeight={700}>{a.field}</Typography><Typography variant="caption" color="text.secondary">{a.user??'Sistema'} · {new Date(a.at).toLocaleString()}</Typography></Box>)}</Stack>}</Paper>
    <Typography variant="caption" color="text.secondary">Control preventivo interno. Verificar requisitos migratorios en fuentes oficiales.</Typography>
    <Dialog open={confirm} onClose={()=>setConfirm(false)} fullWidth><DialogTitle>{d.transfer.isConfirmed?'Actualizar transfer grupal':'Confirmar transfer grupal'}</DialogTitle><DialogContent><Alert severity="info" sx={{my:1}}>Este estado afecta al viaje completo.</Alert><TextField fullWidth multiline minRows={3} label="Notas o referencia" value={notes} onChange={e=>setNotes(e.target.value)}/>{transfer.error&&<Alert severity="error" sx={{mt:2}}>{transfer.error.message}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setConfirm(false)}>Cancelar</Button>{d.transfer.isConfirmed&&<Button color="warning" disabled={transfer.isPending} onClick={()=>transfer.mutate(false)}>Marcar pendiente</Button>}<Button variant="contained" disabled={transfer.isPending} onClick={()=>transfer.mutate(true)}>Confirmar para todo el viaje</Button></DialogActions></Dialog>
  </Stack>
}
