import AddIcon from '@mui/icons-material/Add'
import AirplanemodeActiveIcon from '@mui/icons-material/AirplanemodeActive'
import AttachFileIcon from '@mui/icons-material/AttachFile'
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline'
import EditIcon from '@mui/icons-material/Edit'
import LuggageIcon from '@mui/icons-material/Luggage'
import { Alert, Box, Button, Card, CardContent, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, InputLabel, ListItemText, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { api, postJson, putJson } from '../api'
import { useAuth } from '../auth/AuthProvider'
import { ErrorState, LoadingState } from '../components/LoadingState'
import { StatusChip } from '../components/StatusChip'
import { formatDateTime } from '../format'
import type { Paged, Passenger, VerificationStatus } from '../types'

interface Segment {id?:string;type:'Outbound'|'Return';flightNumber:string;originAirport:string;destinationAirport:string;departureAt:string;arrivalAt:string;originTimeZone?:string;destinationTimeZone?:string;sequence:number}
interface FlightPassenger {passengerId:string;fullName:string;electronicTicketNumber?:string;ticketStatus:VerificationStatus;notes?:string;version:number;updatedAt:string;updatedById?:string}
interface Flight {id:string;status:VerificationStatus;airline?:string;issuingAgency?:string;pnr?:string;generalReference?:string;sourceReference?:string;notes?:string;segments:Segment[];passengers:FlightPassenger[];version:number}
interface EvidenceFile {id:string;originalName:string;legacyDocumentType:string;links:{id:string;flightId?:string;evidenceType:string}[]}
interface LinkImpact {sourceType:string;sourceLabel:string;affectedPassengerCount:number;isShared:boolean;canDeleteIfOrphan:boolean}
interface Baggage {id:string;passengerId:string;fullName:string;flightBookingId?:string;pnr?:string;status:VerificationStatus;checkedBagCount:number;weightPerBagKg:number;appliesOutbound:boolean;appliesReturn:boolean;exceptionReason?:string;sourceReference?:string;evidenceLabel:string;notes?:string;version:number}
interface FlightDraft {status:VerificationStatus;airline:string;issuingAgency:string;pnr:string;sourceReference:string;notes:string;passengerIds:string[];segments:Segment[]}
interface BaggageDraft {passengerId:string;flightBookingId:string;status:VerificationStatus;checkedBagCount:number;weightPerBagKg:number;appliesOutbound:boolean;appliesReturn:boolean;exceptionReason:string;sourceReference:string;notes:string;version:number}
const verification:[VerificationStatus,string][]=[['ToVerify','Por verificar'],['InProgress','En gestión'],['Confirmed','Confirmado'],['NotIncluded','No incluido'],['NotApplicable','No aplica']]
const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,330px),1fr))',gap:2}
const canEdit=(roles?:string[])=>roles?.some(x=>x==='Administrator'||x==='Editor')===true
const local=(value?:string)=>value?value.slice(0,16):''
const emptySegment=(type:'Outbound'|'Return',sequence:number):Segment=>({type,flightNumber:'',originAirport:type==='Outbound'?'ASU':'CUN',destinationAirport:type==='Outbound'?'CUN':'ASU',departureAt:'',arrivalAt:'',sequence})
const emptyFlight=():FlightDraft=>({status:'ToVerify',airline:'',issuingAgency:'',pnr:'',sourceReference:'',notes:'',passengerIds:[],segments:[emptySegment('Outbound',1),emptySegment('Return',2)]})
const emptyBaggage=():BaggageDraft=>({passengerId:'',flightBookingId:'',status:'Confirmed',checkedBagCount:1,weightPerBagKg:23,appliesOutbound:true,appliesReturn:true,exceptionReason:'',sourceReference:'',notes:'',version:0})

function usePassengers(){return useQuery({queryKey:['passengers','options'],queryFn:()=>api<Paged<Passenger>>('/api/passengers?page=1&pageSize=100')})}
function PassengerSelect({value,onChange,people,multiple=true}:{value:string[];onChange:(v:string[])=>void;people:Passenger[];multiple?:boolean}){return <FormControl fullWidth><InputLabel>Pasajeros</InputLabel><Select multiple={multiple} label="Pasajeros" value={value} onChange={e=>onChange(typeof e.target.value==='string'?[e.target.value]:e.target.value)} renderValue={ids=>ids.map(id=>people.find(p=>p.id===id)?.fullName).filter(Boolean).join(', ')}>{people.map(p=><MenuItem key={p.id} value={p.id}><Checkbox checked={value.includes(p.id)}/><ListItemText primary={p.fullName} secondary={p.roomCode}/></MenuItem>)}</Select></FormControl>}

export function FlightsPage(){
  const auth=useAuth(),client=useQueryClient(),people=usePassengers();const q=useQuery({queryKey:['flights'],queryFn:()=>api<Flight[]>('/api/flights')});const [editing,setEditing]=useState<Flight>();const [draft,setDraft]=useState<FlightDraft>();const [ticket,setTicket]=useState<{booking:string;passenger:string;name:string;number:string;status:VerificationStatus;notes:string}>();const [filter,setFilter]=useState('')
  const save=useMutation({mutationFn:async()=>{const removed=(editing?.passengers??[]).filter(x=>!draft!.passengerIds.includes(x.passengerId)&&x.ticketStatus==='Confirmed');let confirmedPassengerRemovalIds:string[]=[];if(removed.length){if(!window.confirm(`Se retirarán ${removed.length} pasajero(s) con ticket confirmado. ¿Confirmás esta acción?`))throw new Error('La edición fue cancelada para preservar los tickets.');confirmedPassengerRemovalIds=removed.map(x=>x.passengerId)}const payload={...draft,version:editing?.version??0,confirmedPassengerRemovalIds,issuingAgency:draft!.issuingAgency||null,sourceReference:draft!.sourceReference||null,notes:draft!.notes||null,generalReference:null,segments:draft!.segments.map((s,index)=>({...s,departureAt:s.departureAt||null,arrivalAt:s.arrivalAt||null,sequence:index+1}))};return editing?putJson(`/api/flights/${editing.id}`,payload):postJson('/api/flights',payload)},onSuccess:async()=>{setDraft(undefined);setEditing(undefined);await Promise.all([client.invalidateQueries({queryKey:['flights']}),client.invalidateQueries({queryKey:['dashboard']}),client.invalidateQueries({queryKey:['passengers']})])}})
  const saveTicket=useMutation({mutationFn:()=>putJson(`/api/flights/${ticket!.booking}/passengers/${ticket!.passenger}/ticket`,{electronicTicketNumber:ticket!.number,status:ticket!.status,notes:ticket!.notes||null,version:q.data?.find(f=>f.id===ticket!.booking)?.passengers.find(p=>p.passengerId===ticket!.passenger)?.version??0}),onSuccess:async()=>{setTicket(undefined);await Promise.all([client.invalidateQueries({queryKey:['flights']}),client.invalidateQueries({queryKey:['dashboard']}),client.invalidateQueries({queryKey:['passengers']})])}})
  const remove=useMutation({mutationFn:(id:string)=>api(`/api/flights/${id}`,{method:'DELETE'}),onSuccess:async()=>{await client.invalidateQueries({queryKey:['flights']})}})
  const upload=useMutation({mutationFn:async({flightId,file}:{flightId:string;file:File})=>{const body=new FormData();body.append('file',file);body.append('documentType','AirTicket');body.append('flightId',flightId);return api('/api/attachments',{method:'POST',body})}})
  const open=(flight?:Flight)=>{setEditing(flight);setDraft(flight?{status:flight.status,airline:flight.airline??'',issuingAgency:flight.issuingAgency??'',pnr:flight.pnr??'',sourceReference:flight.sourceReference??'',notes:flight.notes??'',passengerIds:flight.passengers.map(x=>x.passengerId),segments:flight.segments.map(x=>({...x,departureAt:local(x.departureAt),arrivalAt:local(x.arrivalAt)}))}:emptyFlight())}
  const visible=useMemo(()=>q.data?.filter(f=>`${f.pnr} ${f.airline} ${f.passengers.map(x=>x.fullName).join(' ')}`.toLowerCase().includes(filter.toLowerCase()))??[],[q.data,filter]);if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error}/>;const editable=canEdit(auth.user?.roles),admin=auth.user?.roles.includes('Administrator')
  return <ResourceShell title="Vuelos" subtitle="Reservas, itinerarios y tickets individuales sin perder datos existentes." action={editable&&<Button variant="contained" startIcon={<AddIcon/>} onClick={()=>open()}>Nueva reserva</Button>} empty={!q.data!.length?'Todavía no se cargaron reservas aéreas.':undefined}><TextField fullWidth label="Filtrar por PNR, aerolínea o pasajero" value={filter} onChange={e=>setFilter(e.target.value)}/><Box sx={grid}>{visible.map(f=><Card key={f.id}><CardContent><Stack direction="row" justifyContent="space-between"><AirplanemodeActiveIcon color="secondary"/><StatusChip status={f.status}/></Stack><Typography variant="h2" mt={1}>{f.pnr??'PNR pendiente'}</Typography><Typography>{f.airline??'Aerolínea pendiente'}{f.issuingAgency?` · ${f.issuingAgency}`:''}</Typography>{f.segments.length===0?<Alert severity="info" sx={{my:2}}>Itinerario detallado no cargado.</Alert>:<Stack spacing={1} my={2}>{f.segments.sort((a,b)=>a.sequence-b.sequence).map(s=><Alert key={s.id??s.sequence} severity="info"><b>{s.type==='Outbound'?'Ida':'Regreso'} · {s.flightNumber||'Vuelo pendiente'}</b><br/>{s.originAirport||'—'} → {s.destinationAirport||'—'}<br/>Salida {formatDateTime(s.departureAt)} · llegada {formatDateTime(s.arrivalAt)}</Alert>)}</Stack>}{f.sourceReference&&<Typography variant="body2">Evidencia: {f.sourceReference}</Typography>}{f.passengers.map(x=><Alert key={x.passengerId} severity={x.ticketStatus==='Confirmed'?'success':'warning'} action={editable&&<Button onClick={()=>setTicket({booking:f.id,passenger:x.passengerId,name:x.fullName,number:x.electronicTicketNumber??'',status:x.ticketStatus,notes:x.notes??''})}>Gestionar ticket</Button>}><b>{x.fullName}</b> · {x.electronicTicketNumber??(x.ticketStatus==='Confirmed'?'Número electrónico no informado':'Ticket pendiente')} · <StatusText value={x.ticketStatus}/></Alert>)}{editable&&<Stack direction="row" flexWrap="wrap" gap={1} mt={2}><Button startIcon={<EditIcon/>} onClick={()=>open(f)}>Editar reserva</Button><Button component="label" startIcon={<AttachFileIcon/>}>Adjuntar comprobante<input hidden type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];if(file)upload.mutate({flightId:f.id,file})}}/></Button>{admin&&<Button color="error" startIcon={<DeleteOutlineIcon/>} onClick={()=>{if(window.confirm('¿Eliminar esta reserva aérea? Esta acción queda auditada.'))remove.mutate(f.id)}}>Eliminar</Button>}</Stack>}</CardContent></Card>)}</Box>
    <Dialog open={!!draft} onClose={()=>!save.isPending&&(setDraft(undefined),setEditing(undefined))} fullWidth maxWidth="lg"><DialogTitle>{editing?'Editar reserva aérea':'Nueva reserva aérea'}</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{save.error&&<Alert severity="error">{save.error.message}</Alert>}<Alert severity="info"><b>Estado general del PNR: {verification.find(([value])=>value===(editing?.status??'ToVerify'))?.[1]}</b><br/>Se calcula automáticamente con PNR, aerolínea, pasajeros asociados y sus estados de ticket. El itinerario detallado es opcional.</Alert><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,1fr)'},gap:2}}><TextField required label="Aerolínea" value={draft?.airline??''} onChange={e=>setDraft(x=>x&&({...x,airline:e.target.value}))}/><TextField required label="PNR" value={draft?.pnr??''} onChange={e=>setDraft(x=>x&&({...x,pnr:e.target.value}))}/><TextField label="Agencia emisora" value={draft?.issuingAgency??''} onChange={e=>setDraft(x=>x&&({...x,issuingAgency:e.target.value}))}/><TextField label="Fuente o comprobante real" value={draft?.sourceReference??''} onChange={e=>setDraft(x=>x&&({...x,sourceReference:e.target.value}))}/><TextField label="Notas" value={draft?.notes??''} onChange={e=>setDraft(x=>x&&({...x,notes:e.target.value}))}/></Box><PassengerSelect value={draft?.passengerIds??[]} onChange={passengerIds=>setDraft(x=>x&&({...x,passengerIds}))} people={people.data?.items??[]}/><Typography variant="h2">Segmentos opcionales</Typography>{draft?.segments.map((s,index)=><SegmentFields key={s.id??index} value={s} index={index} onChange={segment=>setDraft(x=>x&&({...x,segments:x.segments.map((item,i)=>i===index?segment:item)}))} onRemove={()=>setDraft(x=>x&&({...x,segments:x.segments.filter((_,i)=>i!==index)}))}/>) }<Button startIcon={<AddIcon/>} onClick={()=>setDraft(x=>x&&({...x,segments:[...x.segments,emptySegment('Outbound',x.segments.length+1)]}))}>Agregar escala</Button></Stack></DialogContent><DialogActions><Button onClick={()=>{setDraft(undefined);setEditing(undefined)}}>Cancelar</Button><Button variant="contained" disabled={!draft?.airline||!draft.pnr||!draft.passengerIds.length||save.isPending} onClick={()=>save.mutate()}>Guardar sin perder tickets</Button></DialogActions></Dialog>
    <Dialog open={!!ticket} onClose={()=>setTicket(undefined)} fullWidth maxWidth="sm"><DialogTitle>Ticket de {ticket?.name}</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Número de ticket electrónico (opcional)" value={ticket?.number??''} onChange={e=>setTicket(t=>t&&({...t,number:e.target.value}))}/>{ticket?.status==='Confirmed'&&!ticket.number&&<Alert severity="info">Número electrónico no informado. El PNR y la aerolínea permiten mantener el ticket confirmado.</Alert>}<TextField select label="Estado individual" value={ticket?.status??'ToVerify'} onChange={e=>setTicket(t=>t&&({...t,status:e.target.value as VerificationStatus}))}>{verification.map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField><TextField label={ticket?.status==='NotApplicable'?'Justificación obligatoria':'Notas'} value={ticket?.notes??''} onChange={e=>setTicket(t=>t&&({...t,notes:e.target.value}))}/>{saveTicket.error&&<Alert severity="error" action={<Button color="inherit" onClick={()=>void q.refetch()}>Recargar datos</Button>}>{saveTicket.error.message}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={()=>setTicket(undefined)}>Cancelar</Button><Button variant="contained" disabled={saveTicket.isPending||(ticket?.status==='NotApplicable'&&!ticket.notes)} onClick={()=>saveTicket.mutate()}>Guardar ticket</Button></DialogActions></Dialog>
    <FlightEvidencePanel flights={q.data!}/>
  </ResourceShell>
}

function FlightEvidencePanel({flights}:{flights:Flight[]}){
  const auth=useAuth(),client=useQueryClient();const [fileId,setFileId]=useState(''),[flightId,setFlightId]=useState(''),[evidenceType,setEvidenceType]=useState('AirTicket')
  const files=useQuery({queryKey:['attachments','flight-management'],queryFn:()=>api<EvidenceFile[]>('/api/attachments')})
  const refresh=async()=>{await Promise.all([client.invalidateQueries({queryKey:['attachments']}),client.invalidateQueries({queryKey:['dashboard']}),client.invalidateQueries({queryKey:['passengers']})])}
  const link=useMutation({mutationFn:()=>postJson(`/api/attachments/${fileId}/links`,{passengerId:null,roomId:null,flightId,baggageId:null,evidenceType}),onSuccess:async()=>{setFileId('');await refresh()}})
  const unlink=useMutation({mutationFn:async({attachmentId,linkId,removePhysical}:{attachmentId:string;linkId:string;removePhysical:boolean})=>{const impact=await api<LinkImpact>(`/api/attachments/${attachmentId}/links/${linkId}/impact`);const warning=`Este comprobante está asociado a ${impact.sourceLabel} y cubre a ${impact.affectedPassengerCount} pasajero(s). Al continuar dejará de contar como evidencia para todo el grupo.`;if(!window.confirm(warning))return;return api(`/api/attachments/${attachmentId}/links/${linkId}?deleteIfOrphan=${removePhysical}`,{method:'DELETE'})},onSuccess:refresh})
  const admin=auth.user?.roles.includes('Administrator')===true
  return <Card variant="outlined"><CardContent><Typography variant="h2">Evidencias compartidas por PNR</Typography><Typography color="text.secondary" mb={2}>El tipo pertenece al vínculo. Un mismo archivo puede ser ticket aéreo y comprobante de maleta sin duplicarse.</Typography><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,1fr) auto'},gap:1.5}}><TextField select label="PNR" value={flightId} onChange={e=>setFlightId(e.target.value)}><MenuItem value="">Seleccionar</MenuItem>{flights.map(f=><MenuItem key={f.id} value={f.id}>{f.pnr??'PNR pendiente'}</MenuItem>)}</TextField><TextField select label="Archivo existente" value={fileId} onChange={e=>setFileId(e.target.value)}><MenuItem value="">Seleccionar</MenuItem>{files.data?.map(file=><MenuItem key={file.id} value={file.id}>{file.originalName}</MenuItem>)}</TextField><TextField select label="Tipo de evidencia" value={evidenceType} onChange={e=>setEvidenceType(e.target.value)}><MenuItem value="AirTicket">Ticket aéreo</MenuItem><MenuItem value="BaggageProof">Comprobante de maleta</MenuItem><MenuItem value="Passport">Pasaporte</MenuItem><MenuItem value="HotelVoucher">Voucher de hotel</MenuItem><MenuItem value="Other">Otro</MenuItem></TextField><Button variant="contained" disabled={!fileId||!flightId||link.isPending} onClick={()=>link.mutate()}>Vincular</Button></Box>{files.data?.flatMap(file=>file.links.filter(item=>item.flightId).map(item=>({file,item}))).map(({file,item})=><Stack key={item.id} direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{sm:'center'}} gap={1} py={1.5} borderBottom="1px solid" borderColor="divider"><Box><Typography fontWeight={800}>{file.originalName} · {item.evidenceType}</Typography><Typography variant="caption">Compartido por {flights.find(f=>f.id===item.flightId)?.pnr??'PNR'} · cubre a {flights.find(f=>f.id===item.flightId)?.passengers.length??0} pasajero(s)</Typography></Box><Stack direction="row" gap={1}><Button color="warning" disabled={unlink.isPending} onClick={()=>unlink.mutate({attachmentId:file.id,linkId:item.id,removePhysical:false})}>Desvincular del PNR</Button>{admin&&<Button color="error" disabled={unlink.isPending} onClick={()=>unlink.mutate({attachmentId:file.id,linkId:item.id,removePhysical:true})}>Eliminar si queda huérfano</Button>}</Stack></Stack>)}{(files.error||link.error||unlink.error)&&<Alert severity="error" sx={{mt:2}}>{files.error?.message??link.error?.message??unlink.error?.message}</Alert>}</CardContent></Card>
}

function SegmentFields({value,index,onChange,onRemove}:{value:Segment;index:number;onChange:(v:Segment)=>void;onRemove:()=>void}){return <Card variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography fontWeight={850}>Segmento {index+1}</Typography><Button color="error" onClick={onRemove}>Quitar</Button></Stack><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,1fr)'},gap:1.5,mt:1}}><TextField select label="Tramo" value={value.type} onChange={e=>onChange({...value,type:e.target.value as 'Outbound'|'Return'})}><MenuItem value="Outbound">Ida</MenuItem><MenuItem value="Return">Regreso</MenuItem></TextField><TextField label="Vuelo" value={value.flightNumber} onChange={e=>onChange({...value,flightNumber:e.target.value})}/><TextField label="Origen" value={value.originAirport} onChange={e=>onChange({...value,originAirport:e.target.value})}/><TextField label="Destino" value={value.destinationAirport} onChange={e=>onChange({...value,destinationAirport:e.target.value})}/><TextField type="datetime-local" label="Salida" value={value.departureAt} onChange={e=>onChange({...value,departureAt:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField type="datetime-local" label="Llegada" value={value.arrivalAt} onChange={e=>onChange({...value,arrivalAt:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/></Box></CardContent></Card>}

export function BaggagePage(){
  const auth=useAuth(),client=useQueryClient(),people=usePassengers();const q=useQuery({queryKey:['baggage'],queryFn:()=>api<Baggage[]>('/api/baggage')});const flights=useQuery({queryKey:['flights'],queryFn:()=>api<Flight[]>('/api/flights')});const [editing,setEditing]=useState<Baggage>();const [draft,setDraft]=useState<BaggageDraft>();const [group,setGroup]=useState<Flight>();const [groupPassengers,setGroupPassengers]=useState<string[]>([]);const [groupResult,setGroupResult]=useState<{updated:number;skipped:{passengerId:string;reason:string}[]}>()
  const save=useMutation({mutationFn:()=>{const payload={...draft,flightBookingId:draft!.flightBookingId||null,exceptionReason:draft!.exceptionReason||null,sourceReference:draft!.sourceReference||null,notes:draft!.notes||null};return editing?putJson(`/api/baggage/${editing.id}`,payload):postJson('/api/baggage',payload)},onSuccess:async()=>{setDraft(undefined);setEditing(undefined);await Promise.all([client.invalidateQueries({queryKey:['baggage']}),client.invalidateQueries({queryKey:['dashboard']}),client.invalidateQueries({queryKey:['passengers']})])}})
  const confirmGroup=useMutation({mutationFn:()=>postJson<{updated:number;skipped:{passengerId:string;reason:string}[]}>('/api/baggage/confirm-group',{flightBookingId:group!.id,passengerIds:groupPassengers,sourceReference:null,notes:null}),onSuccess:async result=>{setGroupResult(result);await Promise.all([client.invalidateQueries({queryKey:['baggage']}),client.invalidateQueries({queryKey:['dashboard']})])}})
  const open=(item?:Baggage)=>{setEditing(item);setDraft(item?{passengerId:item.passengerId,flightBookingId:item.flightBookingId??'',status:item.status,checkedBagCount:item.checkedBagCount,weightPerBagKg:item.weightPerBagKg,appliesOutbound:item.appliesOutbound,appliesReturn:item.appliesReturn,exceptionReason:item.exceptionReason??'',sourceReference:item.sourceReference??'',notes:item.notes??'',version:item.version}:emptyBaggage())};const editable=canEdit(auth.user?.roles);if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error}/>
  return <ResourceShell title="Equipaje" subtitle="Franquicia real de maleta despachada de 23 kg por pasajero y PNR." action={editable&&<Button variant="contained" startIcon={<AddIcon/>} onClick={()=>open()}>Verificar franquicia</Button>} empty={!q.data!.length?'No hay franquicias verificadas todavía.':undefined}><Stack spacing={2}>{editable&&flights.data?.map(f=><Alert key={f.id} severity="info" action={<Button onClick={()=>{setGroup(f);setGroupPassengers(f.passengers.map(x=>x.passengerId));setGroupResult(undefined)}}>Revisar grupo</Button>}>PNR {f.pnr??'pendiente'} · {f.passengers.length} pasajeros · se confirmarán solo quienes tengan ticket efectivo</Alert>)}</Stack><Box sx={grid}>{q.data!.map(b=><Card key={b.id}><CardContent><Stack direction="row" justifyContent="space-between"><LuggageIcon color="secondary"/><StatusChip status={b.status}/></Stack><Typography variant="h2" mt={1}>{b.fullName}</Typography><Typography color="text.secondary">PNR {b.pnr??'sin asociar'}</Typography><Typography fontSize="1.4rem" fontWeight={850} my={1}>{b.checkedBagCount} × {b.weightPerBagKg} kg</Typography><Typography>Ida: {b.appliesOutbound?'Sí':'No'} · regreso: {b.appliesReturn?'Sí':'No'}</Typography>{b.exceptionReason&&<Alert severity="info" sx={{mt:1}}>Excepción: {b.exceptionReason}</Alert>}<Alert severity={b.evidenceLabel==='Sin evidencia'?'warning':'success'} sx={{mt:1}}>Evidencia: {b.evidenceLabel}</Alert>{b.sourceReference&&<Typography variant="body2" mt={1}>Referencia: {b.sourceReference}</Typography>}{editable&&<Button startIcon={<EditIcon/>} onClick={()=>open(b)} sx={{mt:1}}>Editar</Button>}</CardContent></Card>)}</Box>
    <Dialog open={!!draft} onClose={()=>setDraft(undefined)} fullWidth maxWidth="sm"><DialogTitle>{editing?'Editar equipaje':'Verificar franquicia'}</DialogTitle><DialogContent><Stack spacing={2} mt={1}><PassengerSelect value={draft?.passengerId?[draft.passengerId]:[]} onChange={v=>setDraft(x=>x&&({...x,passengerId:v.slice(-1)[0]??''}))} people={people.data?.items??[]} multiple={false}/><TextField required select label="PNR asociado" value={draft?.flightBookingId??''} onChange={e=>setDraft(x=>x&&({...x,flightBookingId:e.target.value}))}>{flights.data?.map(f=><MenuItem key={f.id} value={f.id}>{f.pnr??f.id}</MenuItem>)}</TextField><TextField select label="Estado" value={draft?.status??'ToVerify'} onChange={e=>setDraft(x=>x&&({...x,status:e.target.value as VerificationStatus}))}>{verification.map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField><TextField type="number" label="Cantidad" value={draft?.checkedBagCount??0} onChange={e=>setDraft(x=>x&&({...x,checkedBagCount:Number(e.target.value)}))}/><TextField type="number" label="Peso por maleta (kg)" value={draft?.weightPerBagKg??0} onChange={e=>setDraft(x=>x&&({...x,weightPerBagKg:Number(e.target.value)}))}/><Stack direction="row"><FormControlLabel control={<Checkbox checked={draft?.appliesOutbound??false} onChange={e=>setDraft(x=>x&&({...x,appliesOutbound:e.target.checked}))}/>} label="Cubre ida"/><FormControlLabel control={<Checkbox checked={draft?.appliesReturn??false} onChange={e=>setDraft(x=>x&&({...x,appliesReturn:e.target.checked}))}/>} label="Cubre regreso"/></Stack><TextField required={draft?.status==='NotApplicable'||!(draft?.appliesOutbound&&draft?.appliesReturn)} label="Excepción justificada" value={draft?.exceptionReason??''} onChange={e=>setDraft(x=>x&&({...x,exceptionReason:e.target.value}))}/><TextField label="Fuente o comprobante real" value={draft?.sourceReference??''} onChange={e=>setDraft(x=>x&&({...x,sourceReference:e.target.value}))}/><TextField label="Notas" value={draft?.notes??''} onChange={e=>setDraft(x=>x&&({...x,notes:e.target.value}))}/>{save.error&&<Alert severity="error">{save.error.message}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={()=>setDraft(undefined)}>Cancelar</Button><Button variant="contained" disabled={!draft?.passengerId||!draft.flightBookingId||save.isPending} onClick={()=>save.mutate()}>Guardar</Button></DialogActions></Dialog>
    <Dialog open={!!group} onClose={()=>setGroup(undefined)} fullWidth><DialogTitle>Confirmación grupal · PNR {group?.pnr??'pendiente'}</DialogTitle><DialogContent><Typography mb={2}>Elegí quiénes incluir. El servidor omitirá a quien no tenga PNR, aerolínea y estado de ticket confirmado.</Typography><Stack>{group?.passengers.map(p=><FormControlLabel key={p.passengerId} control={<Checkbox checked={groupPassengers.includes(p.passengerId)} onChange={e=>setGroupPassengers(ids=>e.target.checked?[...ids,p.passengerId]:ids.filter(id=>id!==p.passengerId))}/>} label={`${p.fullName} · ${p.electronicTicketNumber??(p.ticketStatus==='Confirmed'?'Número electrónico no informado':'Ticket pendiente')}`}/>)}</Stack>{groupResult&&<Alert severity={groupResult.skipped.length?'warning':'success'} sx={{mt:2}}>{groupResult.updated} confirmados. {groupResult.skipped.length} omitidos.{groupResult.skipped.map(x=><Typography key={x.passengerId} variant="body2">{group?.passengers.find(p=>p.passengerId===x.passengerId)?.fullName}: {x.reason}</Typography>)}</Alert>}{confirmGroup.error&&<Alert severity="error" sx={{mt:2}}>{confirmGroup.error.message}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setGroup(undefined)}>Cerrar</Button><Button variant="contained" disabled={!groupPassengers.length||confirmGroup.isPending} onClick={()=>confirmGroup.mutate()}>Confirmar 1 × 23 kg, ida y regreso</Button></DialogActions></Dialog>
  </ResourceShell>
}

function StatusText({value}:{value:VerificationStatus}){return <>{verification.find(([v])=>v===value)?.[1]??value}</>}
function ResourceShell({title,subtitle,empty,action,children}:{title:string;subtitle:string;empty?:string;action?:React.ReactNode;children:React.ReactNode}){return <Stack spacing={3}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="h1">{title}</Typography><Typography color="text.secondary">{subtitle}</Typography></Box>{action}</Stack>{empty?<Alert severity="info">{empty}</Alert>:children}</Stack>}
