import AirplanemodeActiveIcon from '@mui/icons-material/AirplanemodeActive'
import AddIcon from '@mui/icons-material/Add'
import LuggageIcon from '@mui/icons-material/Luggage'
import SwapHorizIcon from '@mui/icons-material/SwapHoriz'
import { Alert, Box, Button, Card, CardContent, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, ListItemText, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { api, postJson, putJson } from '../api'
import { useAuth } from '../auth/AuthProvider'
import { ErrorState, LoadingState } from '../components/LoadingState'
import { StatusChip } from '../components/StatusChip'
import type { Paged, Passenger } from '../types'

interface Flight {id:string;status:string;airline?:string;issuingAgency?:string;pnr?:string;segments:{id:string;type:string;flightNumber?:string;originAirport?:string;destinationAirport?:string;departureAt?:string}[];passengerFlights:{passengerId:string;passenger:{fullName:string};electronicTicketNumber?:string;ticketStatus:string}[]}
interface Baggage {id:string;status:string;checkedBagCount:number;weightPerBagKg:number;appliesOutbound:boolean;appliesReturn:boolean;includes23Kg:boolean;passenger:{id:string;fullName:string};flightBooking?:{id:string;pnr?:string}}
interface Transfer {id:string;status:string;company?:string;voucherCode?:string;coverage:string;airport?:string;hotel?:string;passengerTransfers:{passengerId:string;passenger:{fullName:string}}[]}
const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:2}
const canEdit=(roles?:string[])=>roles?.some(x=>x==='Administrator'||x==='Editor')===true

function usePassengers(){return useQuery({queryKey:['passengers','options'],queryFn:()=>api<Paged<Passenger>>('/api/passengers?page=1&pageSize=100')})}
function PassengerSelect({value,onChange,people,multiple=true}:{value:string[];onChange:(v:string[])=>void;people:Passenger[];multiple?:boolean}){return <FormControl fullWidth><InputLabel>Pasajeros</InputLabel><Select multiple={multiple} label="Pasajeros" value={value} onChange={e=>onChange(typeof e.target.value==='string'?[e.target.value]:e.target.value)} renderValue={ids=>ids.map(id=>people.find(p=>p.id===id)?.fullName).filter(Boolean).join(', ')}>{people.map(p=><MenuItem key={p.id} value={p.id}><Checkbox checked={value.includes(p.id)}/><ListItemText primary={p.fullName} secondary={p.roomCode}/></MenuItem>)}</Select></FormControl>}

export function FlightsPage(){
  const auth=useAuth(),client=useQueryClient(),people=usePassengers();const q=useQuery({queryKey:['flights'],queryFn:()=>api<Flight[]>('/api/flight-bookings')});const [open,setOpen]=useState(false);const [passengers,setPassengers]=useState<string[]>([]);const [airline,setAirline]=useState('');const [pnr,setPnr]=useState('');const [out,setOut]=useState({number:'',origin:'ASU',destination:'CUN',departure:''});const [back,setBack]=useState({number:'',origin:'CUN',destination:'ASU',departure:''});const [ticket,setTicket]=useState<{booking:string;passenger:string;name:string;number:string}>();
  const create=useMutation({mutationFn:()=>postJson('/api/flight-bookings',{status:'ToVerify',airline,pnr,issuingAgency:null,generalReference:null,sourceReference:`Carga manual ${pnr}`,notes:null,passengerIds:passengers,segments:[{type:'Outbound',flightNumber:out.number,originAirport:out.origin,destinationAirport:out.destination,departureAt:out.departure||null,arrivalAt:null,originTimeZone:'America/Asuncion',destinationTimeZone:'America/Cancun',sequence:1},{type:'Return',flightNumber:back.number,originAirport:back.origin,destinationAirport:back.destination,departureAt:back.departure||null,arrivalAt:null,originTimeZone:'America/Cancun',destinationTimeZone:'America/Asuncion',sequence:2}]}),onSuccess:async()=>{setOpen(false);await client.invalidateQueries({queryKey:['flights']})}})
  const saveTicket=useMutation({mutationFn:()=>putJson(`/api/flight-bookings/${ticket!.booking}/tickets/${ticket!.passenger}`,{electronicTicketNumber:ticket!.number,status:'Confirmed',notes:'Verificado desde la interfaz'}),onSuccess:async()=>{setTicket(undefined);await client.invalidateQueries({queryKey:['flights']});await client.invalidateQueries({queryKey:['dashboard']})}})
  if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error}/>;return <ResourceShell title="Vuelos" subtitle="Reservas agrupadas por PNR, con segmentos y tickets individuales." action={canEdit(auth.user?.roles)&&<Button variant="contained" startIcon={<AddIcon/>} onClick={()=>setOpen(true)}>Nueva reserva</Button>} empty={!q.data!.length?"Todavía no se cargaron reservas aéreas.":undefined}><Box sx={grid}>{q.data!.map(f=><Card key={f.id}><CardContent><Stack direction="row" justifyContent="space-between"><AirplanemodeActiveIcon color="secondary"/><StatusChip status={f.status}/></Stack><Typography variant="h2" mt={1}>{f.pnr??'PNR pendiente'}</Typography><Typography>{f.airline??f.issuingAgency??'Aerolínea pendiente'}</Typography><Stack spacing={1} my={2}>{f.segments.map(s=><Alert key={s.id} severity="info">{s.type==='Outbound'?'Ida':'Regreso'} · {s.flightNumber??'Vuelo pendiente'} · {s.originAirport??'—'} → {s.destinationAirport??'—'}</Alert>)}</Stack>{f.passengerFlights.map(x=><Alert key={x.passengerId} severity={x.ticketStatus==='Confirmed'?'success':'warning'} action={canEdit(auth.user?.roles)&&<Button onClick={()=>setTicket({booking:f.id,passenger:x.passengerId,name:x.passenger.fullName,number:x.electronicTicketNumber??''})}>{x.electronicTicketNumber?'Editar':'Cargar ticket'}</Button>}>{x.passenger.fullName} · {x.electronicTicketNumber??'ticket pendiente'}</Alert>)}</CardContent></Card>)}</Box><Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="md"><DialogTitle>Nueva reserva aérea</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField required label="Aerolínea" value={airline} onChange={e=>setAirline(e.target.value)}/><TextField required label="PNR" value={pnr} onChange={e=>setPnr(e.target.value)}/><PassengerSelect value={passengers} onChange={setPassengers} people={people.data?.items??[]}/><SegmentFields title="Ida" value={out} onChange={setOut}/><SegmentFields title="Regreso" value={back} onChange={setBack}/>{create.error&&<Alert severity="error">{create.error.message}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" disabled={!airline||!pnr||!passengers.length||create.isPending} onClick={()=>create.mutate()}>Crear reserva</Button></DialogActions></Dialog><Dialog open={!!ticket} onClose={()=>setTicket(undefined)}><DialogTitle>Ticket de {ticket?.name}</DialogTitle><DialogContent><TextField sx={{mt:1}} autoFocus label="Número de ticket electrónico" value={ticket?.number??''} onChange={e=>setTicket(t=>t?{...t,number:e.target.value}:t)}/>{saveTicket.error&&<Alert severity="error" sx={{mt:2}}>{saveTicket.error.message}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setTicket(undefined)}>Cancelar</Button><Button variant="contained" disabled={!ticket?.number||saveTicket.isPending} onClick={()=>saveTicket.mutate()}>Confirmar ticket</Button></DialogActions></Dialog></ResourceShell>
}

function SegmentFields({title,value,onChange}:{title:string;value:{number:string;origin:string;destination:string;departure:string};onChange:(v:{number:string;origin:string;destination:string;departure:string})=>void}){return <Box><Typography fontWeight={800} mb={1}>{title}</Typography><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(4,1fr)'},gap:1}}><TextField label="Vuelo" value={value.number} onChange={e=>onChange({...value,number:e.target.value})}/><TextField label="Origen" value={value.origin} onChange={e=>onChange({...value,origin:e.target.value})}/><TextField label="Destino" value={value.destination} onChange={e=>onChange({...value,destination:e.target.value})}/><TextField type="datetime-local" label="Salida" value={value.departure} onChange={e=>onChange({...value,departure:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/></Box></Box>}

export function BaggagePage(){
  const auth=useAuth(),client=useQueryClient(),people=usePassengers();const q=useQuery({queryKey:['baggage'],queryFn:()=>api<Baggage[]>('/api/baggage')});const flights=useQuery({queryKey:['flights'],queryFn:()=>api<Flight[]>('/api/flight-bookings')});const [open,setOpen]=useState(false);const [passenger,setPassenger]=useState<string[]>([]);const [flight,setFlight]=useState('');const [count,setCount]=useState(1);const [weight,setWeight]=useState(23)
  const save=useMutation({mutationFn:()=>postJson('/api/baggage',{passengerId:passenger[0],flightBookingId:flight||null,status:'Confirmed',checkedBagCount:count,weightPerBagKg:weight,appliesOutbound:true,appliesReturn:true,exceptionReason:null,sourceReference:'Verificación manual',notes:null}),onSuccess:async()=>{setOpen(false);await client.invalidateQueries({queryKey:['baggage']});await client.invalidateQueries({queryKey:['dashboard']})}})
  if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error}/>;return <ResourceShell title="Equipaje" subtitle="Franquicia individual de maleta despachada de 23 kg." action={canEdit(auth.user?.roles)&&<Button variant="contained" startIcon={<AddIcon/>} onClick={()=>setOpen(true)}>Verificar franquicia</Button>} empty={!q.data!.length?'No hay franquicias verificadas todavía.':undefined}><Box sx={grid}>{q.data!.map(b=><Card key={b.id}><CardContent><Stack direction="row" justifyContent="space-between"><LuggageIcon color="secondary"/><StatusChip status={b.status}/></Stack><Typography variant="h2" mt={1}>{b.passenger.fullName}</Typography><Typography color="text.secondary">PNR {b.flightBooking?.pnr??'pendiente'}</Typography><Typography fontSize="1.4rem" fontWeight={850} my={1}>{b.checkedBagCount} × {b.weightPerBagKg} kg</Typography>{!b.includes23Kg&&<Alert severity="error">No alcanza el requisito de 23 kg.</Alert>}</CardContent></Card>)}</Box><Dialog open={open} onClose={()=>setOpen(false)}><DialogTitle>Verificar franquicia</DialogTitle><DialogContent><Stack spacing={2} mt={1}><PassengerSelect value={passenger} onChange={v=>setPassenger(v.slice(-1))} people={people.data?.items??[]} multiple={false}/><TextField select label="PNR asociado" value={flight} onChange={e=>setFlight(e.target.value)}><MenuItem value="">Sin asociar</MenuItem>{flights.data?.map(f=><MenuItem key={f.id} value={f.id}>{f.pnr??f.id}</MenuItem>)}</TextField><TextField type="number" label="Cantidad" value={count} onChange={e=>setCount(Number(e.target.value))}/><TextField type="number" label="Peso por maleta (kg)" value={weight} onChange={e=>setWeight(Number(e.target.value))}/>{save.error&&<Alert severity="error">{save.error.message}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" disabled={!passenger.length||!flight||save.isPending} onClick={()=>save.mutate()}>Confirmar ida y regreso</Button></DialogActions></Dialog></ResourceShell>
}

export function TransfersPage(){
  const auth=useAuth(),client=useQueryClient(),people=usePassengers();const q=useQuery({queryKey:['transfers'],queryFn:()=>api<Transfer[]>('/api/transfers')});const [open,setOpen]=useState(false);const [passengers,setPassengers]=useState<string[]>([]);const [company,setCompany]=useState('');const [voucher,setVoucher]=useState('');const [coverage,setCoverage]=useState('Both')
  const save=useMutation({mutationFn:()=>postJson('/api/transfers',{status:'Confirmed',company,voucherCode:voucher,contact:null,airport:'CUN',hotel:'Grand Palladium Riviera Maya',coverage,arrivalPickupAt:null,departurePickupAt:null,sourceReference:voucher,notes:null,passengerIds:passengers}),onSuccess:async()=>{setOpen(false);await client.invalidateQueries({queryKey:['transfers']});await client.invalidateQueries({queryKey:['dashboard']})}})
  if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error}/>;return <ResourceShell title="Transfers" subtitle="Cobertura grupal aeropuerto ↔ hotel para llegada y salida." action={canEdit(auth.user?.roles)&&<Button variant="contained" startIcon={<AddIcon/>} onClick={()=>setOpen(true)}>Nuevo transfer grupal</Button>} empty={!q.data!.length?'Todavía no se cargaron transfers.':undefined}><Box sx={grid}>{q.data!.map(t=><Card key={t.id}><CardContent><Stack direction="row" justifyContent="space-between"><SwapHorizIcon color="secondary"/><StatusChip status={t.status}/></Stack><Typography variant="h2" mt={1}>{t.company??'Empresa pendiente'}</Typography><Typography>Voucher {t.voucherCode??'pendiente'} · {t.coverage}</Typography><Typography color="text.secondary">{t.airport??'Aeropuerto pendiente'} ↔ {t.hotel??'Hotel pendiente'}</Typography><Typography my={1}>{t.passengerTransfers.length} pasajeros</Typography>{t.coverage!=='Both'&&<Alert severity="warning">Cobertura parcial: falta uno de los tramos.</Alert>}</CardContent></Card>)}</Box><Dialog open={open} onClose={()=>setOpen(false)} fullWidth><DialogTitle>Nuevo transfer grupal</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField required label="Empresa" value={company} onChange={e=>setCompany(e.target.value)}/><TextField required label="Voucher o referencia" value={voucher} onChange={e=>setVoucher(e.target.value)}/><TextField select label="Cobertura" value={coverage} onChange={e=>setCoverage(e.target.value)}><MenuItem value="Arrival">Llegada</MenuItem><MenuItem value="Departure">Salida</MenuItem><MenuItem value="Both">Ambos</MenuItem></TextField><PassengerSelect value={passengers} onChange={setPassengers} people={people.data?.items??[]}/>{save.error&&<Alert severity="error">{save.error.message}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" disabled={!company||!voucher||!passengers.length||save.isPending} onClick={()=>save.mutate()}>Crear y confirmar</Button></DialogActions></Dialog></ResourceShell>
}

function ResourceShell({title,subtitle,empty,action,children}:{title:string;subtitle:string;empty?:string;action?:React.ReactNode;children:React.ReactNode}){return <Stack spacing={3}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="h1">{title}</Typography><Typography color="text.secondary">{subtitle}</Typography></Box>{action}</Stack>{empty?<Alert severity="info">{empty}</Alert>:children}</Stack>}
