import AssignmentIcon from '@mui/icons-material/Assignment'
import SearchIcon from '@mui/icons-material/Search'
import { Alert, Box, Button, Card, CardActionArea, CardContent, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, InputAdornment, LinearProgress, MenuItem, Pagination, Stack, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { api, postJson } from '../api'
import { ErrorState, LoadingState } from '../components/LoadingState'
import { StatusChip } from '../components/StatusChip'
import type { Paged, Passenger } from '../types'
interface RoomOption{id:string;internalCode:string}
export function PassengersPage(){
 const navigate=useNavigate(),client=useQueryClient();const [params,setParams]=useSearchParams();const page=Number(params.get('page')||1);const [search,setSearch]=useState(params.get('search')??'');const [selected,setSelected]=useState(new Set<string>());const [bulkOpen,setBulkOpen]=useState(false);const [room,setRoom]=useState('');const [action,setAction]=useState('');const [due,setDue]=useState('')
 const queryString=new URLSearchParams(params);queryString.set('page',String(page));queryString.set('pageSize','25');const query=useQuery({queryKey:['passengers',queryString.toString()],queryFn:()=>api<Paged<Passenger>>(`/api/passengers?${queryString}`)});const rooms=useQuery({queryKey:['rooms','options'],queryFn:()=>api<RoomOption[]>('/api/rooms')})
 const bulk=useMutation({mutationFn:()=>postJson<{updated:number}>('/api/passengers/bulk-assign',{passengerIds:[...selected],roomReservationId:room||null,flightBookingId:null,nextAction:action||null,nextActionDueDate:due||null}),onSuccess:async()=>{setSelected(new Set());setBulkOpen(false);await client.invalidateQueries({queryKey:['passengers']});await client.invalidateQueries({queryKey:['dashboard']})}})
 const updateSearch=()=>{const next=new URLSearchParams(params);if(search)next.set('search',search);else next.delete('search');next.set('page','1');setParams(next)};const toggle=(id:string)=>setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next})
 if(query.isLoading)return <LoadingState/>;if(query.error)return <ErrorState error={query.error}/>;return <Stack spacing={3}><Box><Typography variant="h1">Pasajeros</Typography><Typography color="text.secondary">Buscá, filtrá y actuá sobre los cinco requisitos de cada persona.</Typography></Box><Card><CardContent><Stack direction={{xs:'column',sm:'row'}} spacing={1.5}><TextField fullWidth value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&updateSearch()} placeholder="Nombre, pasaporte, PNR, ticket o grupo" slotProps={{input:{startAdornment:<InputAdornment position="start"><SearchIcon/></InputAdornment>}}}/><Button variant="contained" onClick={updateSearch}>Buscar</Button></Stack>{selected.size>0&&<Alert severity="info" sx={{mt:2}} action={<Button startIcon={<AssignmentIcon/>} onClick={()=>setBulkOpen(true)}>Asignar datos</Button>}>{selected.size} pasajeros seleccionados</Alert>}</CardContent></Card><Stack spacing={1.5}>{query.data!.items.map(p=><Card key={p.id}><CardActionArea onClick={()=>navigate(`/gestion/pasajeros/${p.id}`,{state:{back:`/gestion/pasajeros?${params}`}})}><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1}><Box><Typography fontWeight={850} fontSize="1.05rem">{p.fullName}</Typography><Typography variant="body2" color="text.secondary">{p.roomCode??'Sin habitación'} · {p.operator??'Sin operadora'} · {p.maskedPassport}</Typography></Box><Stack direction="row" alignItems="center"><StatusChip status={p.overallStatus}/><Checkbox checked={selected.has(p.id)} onClick={e=>e.stopPropagation()} onChange={()=>toggle(p.id)} inputProps={{'aria-label':`Seleccionar ${p.fullName}`}}/></Stack></Stack><Stack direction="row" gap={1} flexWrap="wrap" my={1.5}>{p.requirements.map(r=><Stack key={r.key} direction="row" alignItems="center" gap={.5}><Typography variant="caption" fontWeight={800}>{r.label}</Typography><StatusChip status={r.status}/></Stack>)}</Stack><LinearProgress variant="determinate" value={p.progressPercent} color={p.progressPercent===100?'success':'secondary'} sx={{height:8,borderRadius:4}}/><Typography variant="caption">{p.progressPercent}% · {p.nextAction??'Sin próxima acción'}</Typography>{p.alerts.map(a=><Alert key={a} severity={a.includes('propiedad')?'info':'error'} sx={{mt:1}}>{a}</Alert>)}</CardContent></CardActionArea></Card>)}</Stack><Stack alignItems="center"><Pagination count={Math.max(1,Math.ceil(query.data!.total/25))} page={page} onChange={(_,value)=>{const next=new URLSearchParams(params);next.set('page',String(value));setParams(next)}}/></Stack>
 <Dialog open={bulkOpen} onClose={()=>setBulkOpen(false)} fullWidth><DialogTitle>Asignación masiva</DialogTitle><DialogContent><Typography mb={2}>Se actualizarán {selected.size} pasajeros y el cambio quedará auditado.</Typography><Stack spacing={2}><TextField select label="Código interno de grupo" value={room} onChange={e=>setRoom(e.target.value)}><MenuItem value="">Sin cambio</MenuItem>{rooms.data?.map(r=><MenuItem key={r.id} value={r.id}>{r.internalCode}</MenuItem>)}</TextField><TextField label="Próxima acción" value={action} onChange={e=>setAction(e.target.value)}/><TextField type="date" label="Fecha límite" value={due} onChange={e=>setDue(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/>{bulk.error&&<Alert severity="error">{bulk.error.message}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={()=>setBulkOpen(false)}>Cancelar</Button><Button variant="contained" disabled={(!room&&!action)||bulk.isPending} onClick={()=>bulk.mutate()}>Confirmar</Button></DialogActions></Dialog></Stack>
}
