import { Alert, Box, Card, CardActionArea, CardContent, Chip, Paper, Stack, Typography } from '@mui/material'
import { useQuery } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { api } from '../api'
import { ErrorState, LoadingState } from '../components/LoadingState'
import { formatDate } from '../format'
import type { DashboardData, Paged, Passenger } from '../types'

interface FollowUp {id:string;passengerId?:string;passenger?:string;title:string;dueDate?:string;status:'Open'|'InProgress'|'Closed';priority:string}
const status:Record<string,string>={ToVerify:'Por verificar',InProgress:'En gestión',NotIncluded:'No incluido',NotApplicable:'No aplica',Confirmed:'Confirmado'}
export function PendingPage(){const nav=useNavigate();const peopleQuery=useQuery({queryKey:['pending'],queryFn:()=>api<Paged<Passenger>>('/api/passengers?page=1&pageSize=100')});const dashboard=useQuery({queryKey:['dashboard'],queryFn:()=>api<DashboardData>('/api/dashboard')});const followups=useQuery({queryKey:['follow-ups'],queryFn:()=>api<FollowUp[]>('/api/follow-ups')});if(peopleQuery.isLoading||dashboard.isLoading||followups.isLoading)return <LoadingState/>;if(peopleQuery.error||dashboard.error||followups.error)return <ErrorState error={(peopleQuery.error||dashboard.error||followups.error) as Error}/>;const people=peopleQuery.data!.items.filter(x=>x.overallStatus!=='Ready');const today=new Date().toISOString().slice(0,10);const open=followups.data!.filter(x=>x.status!=='Closed');const overdue=open.filter(x=>x.dueDate&&x.dueDate<today);const upcoming=open.filter(x=>!x.dueDate||x.dueDate>=today);const byRequirement=(key:string)=>people.filter(p=>p.requirements.some(r=>r.key===key&&r.status!=='Confirmed'&&r.status!=='NotApplicable'))
  const sections=[{title:'Inconsistencias críticas',items:people.filter(x=>x.overallStatus==='Attention')},{title:'Tickets pendientes',items:byRequirement('flight')},{title:'Maletas pendientes',items:byRequirement('baggage')},{title:'Documentaciones pendientes',items:byRequirement('documentation')},{title:'Pasaportes pendientes',items:byRequirement('passport')},{title:'Propiedades de hotel pendientes',items:people.filter(x=>x.alerts.some(a=>a.toLowerCase().includes('propiedad')))}]
  return <Stack spacing={3}><Box><Typography variant="h1">Pendientes</Typography><Typography color="text.secondary">Orden operativo: críticos, transfer, seguimientos vencidos y próximos, tickets, maletas, documentación, pasaportes y propiedad.</Typography></Box>{people.length===0&&dashboard.data!.transfer.isConfirmed&&open.length===0?<Alert severity="success">No hay pendientes operativos.</Alert>:<><Section title="Críticos">{(sections[0]?.items??[]).map(p=><PassengerCard key={p.id} passenger={p} onClick={()=>nav(`/gestion/pasajeros/${p.id}`)}/>)}</Section><Section title="Transfer global">{!dashboard.data!.transfer.isConfirmed?<Alert severity="error">Transfer grupal pendiente. Este entregable aparece una sola vez para todo el viaje.</Alert>:<Alert severity="success">Transfer grupal confirmado.</Alert>}</Section><FollowSection title="Seguimientos vencidos" items={overdue}/><FollowSection title="Seguimientos próximos" items={upcoming}/>{sections.slice(1).map(section=><Section key={section.title} title={section.title}>{section.items.length===0?<Typography color="text.secondary">Sin pendientes.</Typography>:section.items.map(p=><PassengerCard key={p.id} passenger={p} onClick={()=>nav(`/gestion/pasajeros/${p.id}`)}/>)}</Section>)}</>}</Stack>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <Paper sx={{p:{xs:2,sm:3}}}><Typography variant="h2" mb={2}>{title}</Typography><Stack spacing={1.5}>{children}</Stack></Paper>}
function PassengerCard({passenger:p,onClick}:{passenger:Passenger;onClick:()=>void}){return <Card variant="outlined"><CardActionArea onClick={onClick}><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between"><Box><Typography fontWeight={850}>{p.fullName}</Typography><Typography color="text.secondary">{p.roomCode??'Sin habitación'} · {p.nextAction??'Sin próxima acción'}</Typography></Box><Chip label={p.overallStatus==='Attention'?'Atención':'Pendiente'} color={p.overallStatus==='Attention'?'error':'warning'}/></Stack><Stack direction="row" gap={1} flexWrap="wrap" mt={1}>{p.requirements.filter(x=>x.status!=='Confirmed'&&x.status!=='NotApplicable').map(x=><Chip key={x.key} label={`${x.label}: ${status[x.status]??x.status}`} variant="outlined" color={x.status==='NotIncluded'?'error':'warning'}/>)}</Stack></CardContent></CardActionArea></Card>}
function FollowSection({title,items}:{title:string;items:FollowUp[]}){return <Section title={title}>{items.length===0?<Typography color="text.secondary">Sin seguimientos.</Typography>:items.map(item=><Alert key={item.id} severity={item.priority==='Critical'?'error':'warning'}><b>{item.title}</b>{item.passenger?` · ${item.passenger}`:''} · vence {formatDate(item.dueDate)}</Alert>)}</Section>}
