import SearchIcon from '@mui/icons-material/Search'
import { Alert, Box, Button, Card, CardActionArea, CardContent, FormControl, InputAdornment, InputLabel, LinearProgress, MenuItem, Pagination, Paper, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { useQuery } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { api } from '../api'
import { ErrorState, LoadingState } from '../components/LoadingState'
import { StatusChip } from '../components/StatusChip'
import type { Paged, PublicDashboard, PublicPassenger } from '../types'

const requirementOptions=[['','Todos los requisitos'],['passport','Pasaporte'],['documentation','Documentación'],['room','Habitación'],['flight','Ticket de vuelo'],['baggage','Maleta de 23 kg']]
export function PublicPassengersPage(){const navigate=useNavigate();const [params,setParams]=useSearchParams();const [search,setSearch]=useState(params.get('search')??'');const [sort,setSort]=useState<'name'|'status'>('name');const page=Number(params.get('page')||1);const queryString=useMemo(()=>{const q=new URLSearchParams(params);q.set('page',String(page));q.set('pageSize','25');return q.toString()},[params,page]);const q=useQuery({queryKey:['public','passengers',queryString],queryFn:()=>api<Paged<PublicPassenger>>(`/api/public/passengers?${queryString}`)});const dashboard=useQuery({queryKey:['public','dashboard'],queryFn:()=>api<PublicDashboard>('/api/public/dashboard')});const applySearch=()=>{const next=new URLSearchParams(params);if(search)next.set('search',search);else next.delete('search');next.set('page','1');setParams(next)};const filter=(key:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);if(key==='requirement'&&!value)next.delete('status');next.set('page','1');setParams(next)}
  if(q.isLoading||dashboard.isLoading)return <LoadingState/>;if(q.error||dashboard.error)return <ErrorState error={(q.error||dashboard.error) as Error} retry={()=>{void q.refetch();void dashboard.refetch()}}/>;const items=[...q.data!.items].sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):a.overallStatus.localeCompare(b.overallStatus));const open=(id:string)=>navigate(`/pasajeros/${id}`,{state:{back:`/pasajeros?${params}`}})
  return <Stack spacing={3}><Box><Typography variant="h1">Pasajeros</Typography><Typography color="text.secondary">Consultá el estado operativo. La búsqueda pública acepta únicamente nombre o código interno de grupo.</Typography></Box><Paper sx={{p:2}}><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,minmax(0,1fr))',lg:'minmax(220px,2fr) repeat(5,minmax(130px,1fr)) auto'},gap:1.5}}><TextField fullWidth label="Buscar" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&applySearch()} slotProps={{input:{startAdornment:<InputAdornment position="start"><SearchIcon/></InputAdornment>}}}/><FormControl><InputLabel>Estado general</InputLabel><Select label="Estado general" value={params.get('overall')??''} onChange={e=>filter('overall',e.target.value)}><MenuItem value="">Todos</MenuItem><MenuItem value="Ready">Listo</MenuItem><MenuItem value="Pending">Pendiente</MenuItem><MenuItem value="Attention">Atención</MenuItem></Select></FormControl><FormControl><InputLabel>Operadora</InputLabel><Select label="Operadora" value={params.get('operatorName')??''} onChange={e=>filter('operatorName',e.target.value)}><MenuItem value="">Todas</MenuItem>{dashboard.data!.operators.map(o=><MenuItem key={o.name} value={o.name}>{o.name}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Requisito</InputLabel><Select label="Requisito" value={params.get('requirement')??''} onChange={e=>filter('requirement',e.target.value)}>{requirementOptions.map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</Select></FormControl><FormControl disabled={!params.get('requirement')}><InputLabel>Estado requisito</InputLabel><Select label="Estado requisito" value={params.get('status')??''} onChange={e=>filter('status',e.target.value)}><MenuItem value="">Pendientes</MenuItem><MenuItem value="Confirmed">Confirmado</MenuItem><MenuItem value="ToVerify">Por verificar</MenuItem><MenuItem value="InProgress">En gestión</MenuItem><MenuItem value="NotIncluded">No incluido</MenuItem><MenuItem value="NotApplicable">No aplica</MenuItem></Select></FormControl><FormControl><InputLabel>Ordenar</InputLabel><Select label="Ordenar" value={sort} onChange={e=>setSort(e.target.value as 'name'|'status')}><MenuItem value="name">Nombre</MenuItem><MenuItem value="status">Estado</MenuItem></Select></FormControl><Button variant="contained" onClick={applySearch}>Buscar</Button></Box></Paper>{items.length===0&&<Alert severity="info">No hay pasajeros que coincidan con los filtros.</Alert>}
    <Stack spacing={1.5} sx={{display:{xs:'flex',md:'none'}}}>{items.map(p=><Card key={p.id}><CardActionArea onClick={()=>open(p.id)}><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Box><Typography fontWeight={900}>{p.name}</Typography><Typography variant="body2" color="text.secondary">{p.roomCode??'Sin grupo'} · {p.operator??'Sin operadora'}</Typography></Box><StatusChip status={p.overallStatus}/></Stack><Stack spacing={1} my={2}>{p.requirements.map(r=><Stack key={r.key} direction="row" justifyContent="space-between" alignItems="center"><Typography variant="body2" fontWeight={750}>{r.label}</Typography><StatusChip status={r.status}/></Stack>)}</Stack><LinearProgress variant="determinate" value={p.progressPercent} color={p.progressPercent===100?'success':'secondary'}/></CardContent></CardActionArea></Card>)}</Stack>
    <TableContainer component={Paper} sx={{display:{xs:'none',md:'block'},maxHeight:'62vh'}}><Table stickyHeader size="small"><TableHead><TableRow><TableCell>Pasajero</TableCell><TableCell>Operadora / grupo</TableCell>{requirementOptions.slice(1).map(([,label])=><TableCell key={label}>{label}</TableCell>)}<TableCell>Estado</TableCell></TableRow></TableHead><TableBody>{items.map(p=><TableRow hover key={p.id} onClick={()=>open(p.id)} sx={{cursor:'pointer'}}><TableCell><Typography fontWeight={800}>{p.name}</Typography><Typography variant="caption">{p.hotel??'Propiedad pendiente'}</Typography></TableCell><TableCell>{p.operator??'—'}<br/>{p.roomCode??'—'}</TableCell>{p.requirements.map(r=><TableCell key={r.key}><StatusChip status={r.status}/></TableCell>)}<TableCell><StatusChip status={p.overallStatus}/><Typography variant="caption" display="block">{p.progressPercent}%</Typography></TableCell></TableRow>)}</TableBody></Table></TableContainer>
    <Stack alignItems="center"><Pagination count={Math.max(1,Math.ceil(q.data!.total/25))} page={page} onChange={(_,value)=>{const next=new URLSearchParams(params);next.set('page',String(value));setParams(next)}}/></Stack></Stack>}
