import EditIcon from '@mui/icons-material/Edit'
import HotelIcon from '@mui/icons-material/Hotel'
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { api, putJson } from '../api'
import { useAuth } from '../auth/AuthProvider'
import { ErrorState, LoadingState } from '../components/LoadingState'
import { StatusChip } from '../components/StatusChip'
import { formatDate } from '../format'
interface Room {id:string;internalCode:string;operator:{id:string;name:string};status:string;hotel?:string;roomType?:string;checkIn?:string;checkOut?:string;nights?:number;occupants:{id:string;fullName:string}[];expectedCapacity:number;capacityOverride:boolean;capacityOverrideReason?:string;sourceReference?:string;hotelReservationNumber?:string;mealPlan?:string;operatorContact?:string;notes?:string;alerts:string[];version:number}
interface Operator {id:string;name:string}
export function RoomsPage(){
  const auth=useAuth(),client=useQueryClient();const q=useQuery({queryKey:['rooms'],queryFn:()=>api<Room[]>('/api/rooms')});const operators=useQuery({queryKey:['operators'],queryFn:()=>api<Operator[]>('/api/operators')});const [editing,setEditing]=useState<Room>();const [draft,setDraft]=useState<Partial<Room>>({})
  const save=useMutation({mutationFn:()=>putJson(`/api/rooms/${editing!.id}`,{internalCode:draft.internalCode,operatorId:draft.operator?.id,status:draft.status,hotel:draft.hotel||null,roomType:draft.roomType||null,expectedCapacity:Number(draft.expectedCapacity),capacityOverride:Boolean(draft.capacityOverride),capacityOverrideReason:draft.capacityOverrideReason||null,checkIn:draft.checkIn||null,checkOut:draft.checkOut||null,hotelReservationNumber:draft.hotelReservationNumber||null,mealPlan:draft.mealPlan||null,sourceReference:draft.sourceReference||null,operatorContact:draft.operatorContact||null,notes:draft.notes||null,version:editing!.version}),onSuccess:async()=>{setEditing(undefined);await client.invalidateQueries({queryKey:['rooms']});await client.invalidateQueries({queryKey:['dashboard']})}})
  const open=(room:Room)=>{setEditing(room);setDraft({...room})};const field=(name:keyof Room)=>(e:React.ChangeEvent<HTMLInputElement>)=>setDraft(x=>({...x,[name]:e.target.value}));const editable=auth.user?.roles.some(x=>x==='Administrator'||x==='Editor')
  if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error}/>;return <Stack spacing={3}><Box><Typography variant="h1">Habitaciones</Typography><Typography color="text.secondary">{q.data!.length} códigos internos de grupo. No representan el número físico asignado por el hotel.</Typography></Box><Box sx={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,310px),1fr))',gap:2}}>{q.data!.map(r=><Card key={r.id}><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Stack direction="row" gap={1} alignItems="center"><HotelIcon color="secondary"/><Typography variant="h2">{r.internalCode}</Typography></Stack><StatusChip status={r.status}/></Stack><Typography fontWeight={800} mt={1}>{r.operator.name}</Typography><Typography>{r.hotel??'Propiedad sin especificar'}</Typography><Typography color="text.secondary">{r.roomType??'Tipo pendiente'} · {r.nights??'—'} noches</Typography><Typography mt={1}>{formatDate(r.checkIn)} → {formatDate(r.checkOut)}</Typography><Stack direction="row" flexWrap="wrap" gap={.7} my={1.5}>{r.occupants.map(x=><Chip key={x.id} label={x.fullName} size="small"/>)}<Chip label={`${r.occupants.length}/${r.expectedCapacity}`} color={r.occupants.length>r.expectedCapacity?'error':'default'} size="small"/></Stack>{r.alerts.map(a=><Alert key={a} severity={a.includes('Propiedad')?'info':'error'} sx={{mt:1}}>{a}</Alert>)}{!r.sourceReference&&<Alert severity="warning" sx={{mt:1}}>Falta fuente o referencia.</Alert>}{editable&&<Button startIcon={<EditIcon/>} sx={{mt:2}} onClick={()=>open(r)}>Editar habitación</Button>}</CardContent></Card>)}</Box>
    <Dialog open={!!editing} onClose={()=>setEditing(undefined)} fullWidth maxWidth="md"><DialogTitle>Editar {editing?.internalCode}</DialogTitle><DialogContent><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1fr 1fr'},gap:2,mt:1}}><TextField required label="Código interno" value={draft.internalCode??''} onChange={field('internalCode')}/><TextField select label="Operadora" value={draft.operator?.id??''} onChange={e=>setDraft(x=>({...x,operator:operators.data?.find(o=>o.id===e.target.value)}))}>{operators.data?.map(o=><MenuItem key={o.id} value={o.id}>{o.name}</MenuItem>)}</TextField><TextField select label="Estado" value={draft.status??'ToVerify'} onChange={field('status')}><MenuItem value="ToVerify">Por verificar</MenuItem><MenuItem value="InProgress">En gestión</MenuItem><MenuItem value="Confirmed">Confirmado</MenuItem><MenuItem value="NotIncluded">No incluido</MenuItem><MenuItem value="NotApplicable">No aplica</MenuItem></TextField><TextField label="Hotel / propiedad" value={draft.hotel??''} onChange={field('hotel')}/><TextField label="Tipo de habitación" value={draft.roomType??''} onChange={field('roomType')}/><TextField type="number" label="Capacidad esperada" value={draft.expectedCapacity??0} onChange={field('expectedCapacity')}/><TextField type="date" label="Check-in" value={draft.checkIn??''} onChange={field('checkIn')} slotProps={{inputLabel:{shrink:true}}}/><TextField type="date" label="Check-out" value={draft.checkOut??''} onChange={field('checkOut')} slotProps={{inputLabel:{shrink:true}}}/><TextField label="Reserva de hotel" value={draft.hotelReservationNumber??''} onChange={field('hotelReservationNumber')}/><TextField label="Plan de comidas" value={draft.mealPlan??''} onChange={field('mealPlan')}/><TextField required={draft.status==='Confirmed'} label="Fuente / voucher" value={draft.sourceReference??''} onChange={field('sourceReference')}/><TextField label="Contacto operadora" value={draft.operatorContact??''} onChange={field('operatorContact')}/></Box><TextField fullWidth multiline minRows={3} sx={{mt:2}} label="Observaciones" value={draft.notes??''} onChange={field('notes')}/>{save.error&&<Alert severity="error" sx={{mt:2}}>{save.error.message}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setEditing(undefined)}>Cancelar</Button><Button variant="contained" disabled={save.isPending||!draft.internalCode||!draft.operator?.id} onClick={()=>save.mutate()}>Guardar cambios</Button></DialogActions></Dialog>
  </Stack>
}
