import HotelIcon from '@mui/icons-material/Hotel'
import { Alert, Box, Card, CardContent, Chip, Stack, Typography } from '@mui/material'
import { useQuery } from '@tanstack/react-query'
import { api } from '../api'
import { ErrorState, LoadingState } from '../components/LoadingState'
import { StatusChip } from '../components/StatusChip'
import { formatDate } from '../format'

interface Room {id:string;internalCode:string;operator:string;status:string;hotel?:string;roomType?:string;checkIn?:string;checkOut?:string;nights?:number;occupants:{id:string;fullName:string}[];expectedCapacity:number;sourceReference?:string;hotelReservationNumber?:string;operatorContact?:string;notes?:string;alerts:string[]}
export function RoomsPage(){const q=useQuery({queryKey:['rooms'],queryFn:()=>api<Room[]>('/api/rooms')});if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error}/>;return <Stack spacing={3}><Box><Typography variant="h1">Habitaciones</Typography><Typography color="text.secondary">{q.data!.length} códigos internos de grupo. No representan el número físico asignado por el hotel.</Typography></Box><Box sx={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(310px,1fr))',gap:2}}>{q.data!.map(r=><Card key={r.id}><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Stack direction="row" gap={1} alignItems="center"><HotelIcon color="secondary"/><Typography variant="h2">{r.internalCode}</Typography></Stack><StatusChip status={r.status}/></Stack><Typography fontWeight={800} mt={1}>{r.operator}</Typography><Typography>{r.hotel??'Propiedad sin especificar'}</Typography><Typography color="text.secondary">{r.roomType??'Tipo pendiente'} · {r.nights??'—'} noches</Typography><Typography mt={1}>{formatDate(r.checkIn)} → {formatDate(r.checkOut)}</Typography><Stack direction="row" flexWrap="wrap" gap={.7} my={1.5}>{r.occupants.map(x=><Chip key={x.id} label={x.fullName} size="small"/>)}<Chip label={`${r.occupants.length}/${r.expectedCapacity}`} color={r.occupants.length>r.expectedCapacity?'error':'default'} size="small"/></Stack>{r.alerts.map(a=><Alert key={a} severity={a.includes('Propiedad')?'info':'error'} sx={{mt:1}}>{a}</Alert>)}{!r.sourceReference&&<Alert severity="warning" sx={{mt:1}}>Falta fuente o referencia.</Alert>}</CardContent></Card>)}</Box></Stack>}
