import AttachFileIcon from '@mui/icons-material/AttachFile'
import EditIcon from '@mui/icons-material/Edit'
import GroupIcon from '@mui/icons-material/Group'
import HotelIcon from '@mui/icons-material/Hotel'
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, ListItemText, MenuItem, Stack, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { api, putJson } from '../api'
import { useAuth } from '../auth/AuthProvider'
import { ErrorState, LoadingState } from '../components/LoadingState'
import { StatusChip } from '../components/StatusChip'
import { formatDate } from '../format'
import type { Paged, Passenger, VerificationStatus } from '../types'

interface Room {id:string;internalCode:string;operator:{id:string;name:string};status:VerificationStatus;hotel?:string;roomType?:string;checkIn?:string;checkOut?:string;nights?:number;occupants:{id:string;fullName:string}[];expectedCapacity:number;capacityOverride:boolean;capacityOverrideReason?:string;sourceReference?:string;hotelReservationNumber?:string;mealPlan?:string;operatorContact?:string;notes?:string;alerts:string[];version:number}
interface Operator {id:string;name:string}
const verification:[VerificationStatus,string][]=[['ToVerify','Por verificar'],['InProgress','En gestión'],['Confirmed','Confirmado'],['NotIncluded','No incluido'],['NotApplicable','No aplica']]

export function RoomsPage(){
  const auth=useAuth(),client=useQueryClient();const q=useQuery({queryKey:['rooms'],queryFn:()=>api<Room[]>('/api/rooms')});const operators=useQuery({queryKey:['operators'],queryFn:()=>api<Operator[]>('/api/operators')});const people=useQuery({queryKey:['passengers','room-options'],queryFn:()=>api<Paged<Passenger>>('/api/passengers?page=1&pageSize=100')});const [editing,setEditing]=useState<Room>();const [draft,setDraft]=useState<Partial<Room>>({});const [occupantsRoom,setOccupantsRoom]=useState<Room>();const [occupantIds,setOccupantIds]=useState<string[]>([]);const [operatorFilter,setOperatorFilter]=useState('');const [statusFilter,setStatusFilter]=useState('');const [propertyPending,setPropertyPending]=useState(false)
  const save=useMutation({mutationFn:()=>putJson(`/api/rooms/${editing!.id}`,{internalCode:draft.internalCode,operatorId:draft.operator?.id,status:draft.status,hotel:draft.hotel||null,roomType:draft.roomType||null,expectedCapacity:Number(draft.expectedCapacity),capacityOverride:Boolean(draft.capacityOverride),capacityOverrideReason:draft.capacityOverrideReason||null,checkIn:draft.checkIn||null,checkOut:draft.checkOut||null,hotelReservationNumber:draft.hotelReservationNumber||null,mealPlan:draft.mealPlan||null,sourceReference:draft.sourceReference||null,operatorContact:draft.operatorContact||null,notes:draft.notes||null,version:editing!.version}),onSuccess:async()=>{setEditing(undefined);await Promise.all([client.invalidateQueries({queryKey:['rooms']}),client.invalidateQueries({queryKey:['dashboard']}),client.invalidateQueries({queryKey:['passengers']})])}})
  const saveOccupants=useMutation({mutationFn:()=>putJson(`/api/rooms/${occupantsRoom!.id}/occupants`,{passengerIds:occupantIds,version:occupantsRoom!.version}),onSuccess:async()=>{setOccupantsRoom(undefined);await Promise.all([client.invalidateQueries({queryKey:['rooms']}),client.invalidateQueries({queryKey:['passengers']}),client.invalidateQueries({queryKey:['dashboard']})])}})
  const upload=useMutation({mutationFn:async({roomId,file}:{roomId:string;file:File})=>{const body=new FormData();body.append('file',file);body.append('documentType','HotelVoucher');body.append('roomId',roomId);return api('/api/attachments',{method:'POST',body})}})
  const open=(room:Room)=>{setEditing(room);setDraft({...room})};const field=(name:keyof Room)=>(e:React.ChangeEvent<HTMLInputElement>)=>setDraft(x=>({...x,[name]:e.target.value}));const editable=auth.user?.roles.some(x=>x==='Administrator'||x==='Editor');const filtered=useMemo(()=>q.data?.filter(room=>(!operatorFilter||room.operator.name===operatorFilter)&&(!statusFilter||room.status===statusFilter)&&(!propertyPending||room.alerts.some(x=>x.toLowerCase().includes('propiedad'))))??[],[q.data,operatorFilter,statusFilter,propertyPending])
  if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error}/>;return <Stack spacing={3}><Box><Typography variant="h1">Habitaciones</Typography><Typography color="text.secondary">{q.data!.length} códigos internos de grupo; no representan el número físico asignado por el hotel.</Typography></Box><Card><CardContent><Stack direction={{xs:'column',md:'row'}} gap={1.5}><TextField select label="Operadora" value={operatorFilter} onChange={e=>setOperatorFilter(e.target.value)} sx={{minWidth:190}}><MenuItem value="">Todas</MenuItem>{operators.data?.map(o=><MenuItem key={o.id} value={o.name}>{o.name}</MenuItem>)}</TextField><TextField select label="Estado" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} sx={{minWidth:190}}><MenuItem value="">Todos</MenuItem>{verification.map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField><FormControlLabel control={<Checkbox checked={propertyPending} onChange={e=>setPropertyPending(e.target.checked)}/>} label="Solo propiedad pendiente"/></Stack></CardContent></Card><Box sx={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,310px),1fr))',gap:2}}>{filtered.map(r=><Card key={r.id}><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Stack direction="row" gap={1} alignItems="center"><HotelIcon color="secondary"/><Typography variant="h2">{r.internalCode}</Typography></Stack><StatusChip status={r.status}/></Stack><Typography fontWeight={800} mt={1}>{r.operator.name}</Typography><Typography>{r.hotel??'Propiedad sin especificar'}</Typography><Typography color="text.secondary">{r.roomType??'Tipo pendiente'} · {r.nights??'—'} noches</Typography><Typography mt={1}>{formatDate(r.checkIn)} → {formatDate(r.checkOut)}</Typography><Stack direction="row" flexWrap="wrap" gap={.7} my={1.5}>{r.occupants.map(x=><Chip key={x.id} label={x.fullName} size="small"/>)}<Chip label={`${r.occupants.length}/${r.expectedCapacity}`} color={r.occupants.length>r.expectedCapacity?'error':'default'} size="small"/></Stack>{r.capacityOverride&&<Alert severity="warning" sx={{mt:1}}>Excepción de capacidad: {r.capacityOverrideReason}</Alert>}{r.alerts.map(a=><Alert key={a} severity={a.toLowerCase().includes('propiedad')?'info':'error'} sx={{mt:1}}>{a}</Alert>)}{!r.sourceReference&&<Alert severity="warning" sx={{mt:1}}>Falta fuente o referencia real.</Alert>}{editable&&<Stack direction="row" flexWrap="wrap" gap={1} mt={2}><Button startIcon={<EditIcon/>} onClick={()=>open(r)}>Editar</Button><Button startIcon={<GroupIcon/>} onClick={()=>{setOccupantsRoom(r);setOccupantIds(r.occupants.map(x=>x.id))}}>Ocupantes</Button><Button component="label" startIcon={<AttachFileIcon/>}>Adjuntar voucher<input hidden type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];if(file)upload.mutate({roomId:r.id,file})}}/></Button></Stack>}</CardContent></Card>)}</Box>
    <Dialog open={!!editing} onClose={()=>setEditing(undefined)} fullWidth maxWidth="md"><DialogTitle>Editar {editing?.internalCode}</DialogTitle><DialogContent><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1fr 1fr'},gap:2,mt:1}}><TextField required label="Código interno" value={draft.internalCode??''} onChange={field('internalCode')}/><TextField select label="Operadora" value={draft.operator?.id??''} onChange={e=>setDraft(x=>({...x,operator:operators.data?.find(o=>o.id===e.target.value)}))}>{operators.data?.map(o=><MenuItem key={o.id} value={o.id}>{o.name}</MenuItem>)}</TextField><TextField select label="Estado" value={draft.status??'ToVerify'} onChange={field('status')}>{verification.map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField><TextField label="Hotel / propiedad" value={draft.hotel??''} onChange={field('hotel')}/><TextField label="Tipo de habitación" value={draft.roomType??''} onChange={field('roomType')}/><TextField type="number" label="Capacidad esperada" value={draft.expectedCapacity??0} onChange={field('expectedCapacity')}/><TextField type="date" label="Check-in" value={draft.checkIn??''} onChange={field('checkIn')} slotProps={{inputLabel:{shrink:true}}}/><TextField type="date" label="Check-out" value={draft.checkOut??''} onChange={field('checkOut')} slotProps={{inputLabel:{shrink:true}}}/><TextField label="Reserva de hotel" value={draft.hotelReservationNumber??''} onChange={field('hotelReservationNumber')}/><TextField label="Plan de comidas" value={draft.mealPlan??''} onChange={field('mealPlan')}/><TextField required={draft.status==='Confirmed'} label="Fuente / voucher real" value={draft.sourceReference??''} onChange={field('sourceReference')}/><TextField label="Contacto operadora" value={draft.operatorContact??''} onChange={field('operatorContact')}/></Box><FormControlLabel sx={{mt:2}} control={<Checkbox checked={Boolean(draft.capacityOverride)} onChange={e=>setDraft(x=>({...x,capacityOverride:e.target.checked}))}/>} label="Permitir excepción de capacidad"/>{draft.capacityOverride&&<TextField required fullWidth label="Justificación de la excepción" value={draft.capacityOverrideReason??''} onChange={field('capacityOverrideReason')}/>}<TextField fullWidth multiline minRows={3} sx={{mt:2}} label={draft.status==='NotApplicable'?'Justificación obligatoria':'Observaciones'} value={draft.notes??''} onChange={field('notes')}/>{save.error&&<Alert severity="error" sx={{mt:2}}>{save.error.message}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setEditing(undefined)}>Cancelar</Button><Button variant="contained" disabled={save.isPending||!draft.internalCode||!draft.operator?.id||Boolean(draft.capacityOverride&&!draft.capacityOverrideReason)} onClick={()=>save.mutate()}>Guardar cambios</Button></DialogActions></Dialog>
    <Dialog open={!!occupantsRoom} onClose={()=>setOccupantsRoom(undefined)} fullWidth><DialogTitle>Ocupantes de {occupantsRoom?.internalCode}</DialogTitle><DialogContent><Typography mb={2}>Mover un pasajero a esta habitación lo quitará de su grupo anterior. Capacidad: {occupantsRoom?.expectedCapacity}.</Typography><TextField select fullWidth label="Pasajeros" value={occupantIds} onChange={e=>setOccupantIds(typeof e.target.value==='string'?[e.target.value]:e.target.value)} slotProps={{select:{multiple:true,renderValue:selected=>(selected as string[]).map(id=>people.data?.items.find(p=>p.id===id)?.fullName).filter(Boolean).join(', ')}}}>{people.data?.items.map(p=><MenuItem key={p.id} value={p.id}><Checkbox checked={occupantIds.includes(p.id)}/><ListItemText primary={p.fullName} secondary={p.roomCode}/></MenuItem>)}</TextField>{saveOccupants.error&&<Alert severity="error" sx={{mt:2}}>{saveOccupants.error.message}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setOccupantsRoom(undefined)}>Cancelar</Button><Button variant="contained" disabled={saveOccupants.isPending} onClick={()=>saveOccupants.mutate()}>Guardar ocupantes</Button></DialogActions></Dialog>
  </Stack>
}
