import AddIcon from '@mui/icons-material/Add'
import { Alert, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, Switch, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { api, postJson, putJson } from '../api'
import { ErrorState, LoadingState } from '../components/LoadingState'
interface ManagedUser {id:string;email:string;displayName:string;isActive:boolean;roles:string[]}
export function UsersPage(){
 const client=useQueryClient();const q=useQuery({queryKey:['users'],queryFn:()=>api<ManagedUser[]>('/api/users')});const [open,setOpen]=useState(false);const [email,setEmail]=useState('');const [name,setName]=useState('');const [role,setRole]=useState('Viewer');const [password,setPassword]=useState('');const [reset,setReset]=useState<ManagedUser>();const [newPassword,setNewPassword]=useState('')
 const create=useMutation({mutationFn:()=>postJson('/api/users',{email,displayName:name,role,initialPassword:password}),onSuccess:async()=>{setOpen(false);setPassword('');await client.invalidateQueries({queryKey:['users']})}})
 const update=useMutation({mutationFn:(u:ManagedUser)=>putJson(`/api/users/${u.id}`,{displayName:u.displayName,role:u.roles[0]??'Viewer',isActive:!u.isActive}),onSuccess:async()=>client.invalidateQueries({queryKey:['users']})})
 const resetPassword=useMutation({mutationFn:()=>postJson(`/api/users/${reset!.id}/reset-password`,{newPassword}),onSuccess:()=>{setReset(undefined);setNewPassword('')}})
 if(q.isLoading)return <LoadingState/>;if(q.error)return <ErrorState error={q.error}/>;return <Stack spacing={3}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><div><Typography variant="h1">Usuarios</Typography><Typography color="text.secondary">Roles, acceso y restablecimiento seguro de contraseñas.</Typography></div><Button variant="contained" startIcon={<AddIcon/>} onClick={()=>setOpen(true)}>Crear usuario</Button></Stack>{q.data!.map(u=><Card key={u.id}><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><div><Typography variant="h2">{u.displayName}</Typography><Typography>{u.email}</Typography><Typography color="text.secondary">{u.roles.join(', ')}</Typography></div><Stack direction="row" alignItems="center" gap={1}><Typography>{u.isActive?'Activo':'Desactivado'}</Typography><Switch checked={u.isActive} onChange={()=>update.mutate(u)} inputProps={{'aria-label':`Acceso de ${u.displayName}`}}/><Button onClick={()=>setReset(u)}>Restablecer clave</Button></Stack></Stack></CardContent></Card>)}
 <Dialog open={open} onClose={()=>setOpen(false)}><DialogTitle>Crear usuario</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Nombre visible" value={name} onChange={e=>setName(e.target.value)}/><TextField label="Correo" type="email" value={email} onChange={e=>setEmail(e.target.value)}/><TextField select label="Rol" value={role} onChange={e=>setRole(e.target.value)}><MenuItem value="Administrator">Administrador</MenuItem><MenuItem value="Editor">Editor</MenuItem><MenuItem value="Viewer">Consulta</MenuItem></TextField><TextField label="Contraseña inicial" type="password" value={password} onChange={e=>setPassword(e.target.value)} helperText="Mínimo 12 caracteres, mayúscula, minúscula, número y símbolo."/>{create.error&&<Alert severity="error">{create.error.message}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" disabled={!email||!name||password.length<12||create.isPending} onClick={()=>create.mutate()}>Crear</Button></DialogActions></Dialog>
 <Dialog open={!!reset} onClose={()=>setReset(undefined)}><DialogTitle>Restablecer contraseña</DialogTitle><DialogContent><Alert severity="warning" sx={{my:1}}>La clave no se mostrará ni quedará registrada en auditoría.</Alert><TextField label="Nueva contraseña" type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/>{resetPassword.error&&<Alert severity="error" sx={{mt:2}}>{resetPassword.error.message}</Alert>}</DialogContent><DialogActions><Button onClick={()=>setReset(undefined)}>Cancelar</Button><Button variant="contained" disabled={newPassword.length<12||resetPassword.isPending} onClick={()=>resetPassword.mutate()}>Restablecer</Button></DialogActions></Dialog></Stack>
}
