import DownloadIcon from '@mui/icons-material/Download'
import UploadFileIcon from '@mui/icons-material/UploadFile'
import { Alert, Box, Button, Card, CardContent, CircularProgress, Divider, List, ListItem, ListItemText, Stack, Typography } from '@mui/material'
import { useState } from 'react'
import { api } from '../api'

interface Summary {passengerRows:number;roomRows:number;added:number;updated:number;unchanged:number;errors:number;canCommit:boolean;issues:{level:string;sheet:string;row?:number;message:string}[];expectedComparison:Record<string,number>;importRunId?:string}
export function ImportExportPage(){
  const [file,setFile]=useState<File>(); const [summary,setSummary]=useState<Summary>(); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  const send=async(commit:boolean)=>{if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);setSummary(await api<Summary>(`/api/imports/${commit?'commit':'preview'}`,{method:'POST',body:form}))}catch(e){setError(e instanceof Error?e.message:'Falló la importación.')}finally{setBusy(false)}}
  return <Stack spacing={3}><Box><Typography variant="h1">Importar y exportar</Typography><Typography color="text.secondary">El dry-run no modifica datos. Revisá advertencias antes de confirmar.</Typography></Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1.2fr .8fr'},gap:3}}>
    <Card><CardContent><Typography variant="h2">Importar XLSX</Typography><Button component="label" startIcon={<UploadFileIcon/>} variant="outlined" sx={{my:2}}>Elegir archivo<input hidden type="file" accept=".xlsx" onChange={e=>{setFile(e.target.files?.[0]);setSummary(undefined)}}/></Button>{file&&<Alert severity="info">{file.name} · {(file.size/1024).toFixed(1)} KB</Alert>}{error&&<Alert severity="error" sx={{mt:2}}>{error}</Alert>}<Stack direction="row" gap={1} mt={2}><Button variant="contained" disabled={!file||busy} onClick={()=>void send(false)}>Vista previa</Button>{summary?.canCommit&&<Button color="success" variant="contained" disabled={busy} onClick={()=>void send(true)}>Confirmar importación</Button>}{busy&&<CircularProgress size={28}/>}</Stack>{summary&&<Box mt={3}><Divider/><Typography variant="h2" mt={2}>Resultado</Typography><Typography>{summary.passengerRows} pasajeros · {summary.roomRows} habitaciones</Typography><Typography>{summary.added} altas · {summary.updated} actualizaciones · {summary.unchanged} sin cambios · {summary.errors} errores</Typography>{summary.importRunId&&<Alert severity="success" sx={{mt:1}}>Importación confirmada. ID {summary.importRunId}</Alert>}<List>{summary.issues.map((i,n)=><ListItem key={n}><ListItemText primary={i.message} secondary={`${i.level} · ${i.sheet}${i.row?` · fila ${i.row}`:''}`} primaryTypographyProps={{color:i.level==='Error'?'error.main':i.level==='Advertencia'?'warning.main':'text.primary'}}/></ListItem>)}</List></Box>}</CardContent></Card>
    <Card><CardContent><Typography variant="h2">Exportaciones</Typography><Typography color="text.secondary" mb={2}>Los archivos se generan desde la base de datos actual.</Typography><Stack spacing={1.5}><Button href="/api/exports/control.xlsx" startIcon={<DownloadIcon/>} variant="contained">Descargar control XLSX</Button><Button href="/api/exports/passengers.csv" startIcon={<DownloadIcon/>} variant="outlined">Pasajeros CSV</Button><Button href="/api/exports/pending.xlsx" startIcon={<DownloadIcon/>} variant="outlined">Reporte de pendientes XLSX</Button><Button href="/api/exports/backup.json" startIcon={<DownloadIcon/>} variant="outlined">Respaldo JSON (admin)</Button></Stack><Alert severity="info" sx={{mt:3}}>El control incluye Dashboard, Control pasajeros, Habitaciones y Fuentes y uso. Los pasaportes permanecen enmascarados.</Alert></CardContent></Card>
  </Box></Stack>
}
